# Generated by Django 5.0.6 on 2026-07-02 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('supplier', 'Supplier'), ('admin', 'Admin')], default='buyer', max_length=20),
        ),
    ]
